// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[gif]/detail.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/GifEngine.tsx";
import * as $$2 from "./islands/SearchBar.tsx";

const manifest = {
  routes: {
    "./routes/[gif]/detail.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/GifEngine.tsx": $$1,
    "./islands/SearchBar.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
